[versions]
kotlinVer = "1.6.10"
agpVer = "7.1.2"
polyfillVer = "0.6.0.2-SNAPSHOT"
mockitoVer = "3.9.0"
kspVer = "1.6.10-1.0.4"

[libraries]
koncat-processor-api = { module = "me.2bab.koncat:processor-api", version = "*"}
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agpVer" }
kotlin-std = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlinVer" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVer" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm", version = "1.3.1" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kspVer" }
ksp-impl = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "kspVer" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "kspVer" }
polyfill-main = { module = "me.2bab:polyfill", version.ref = "polyfillVer" }
junit = { module = "junit:junit", version = "4.12" }

[bundles]

[plugins]