{
  "formatVersion": "1.1",
  "component": {
    "group": "me.2bab",
    "module": "koncat-sample-lib2",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "koncat-sample-lib2-1.0.aar",
          "url": "koncat-sample-lib2-1.0.aar",
          "size": 2317,
          "sha512": "ce27b890cc16cbcfce6aae3c52fcdd85445ec76e05872718698ed23548852fe2ccac7d0709298c3792bd755137fe958896787ce6d13be418570080216e44326a",
          "sha256": "310509022d1089d0ae643a336c6c532e9eb8e3b55b22bb64346bb24a82eb80c3",
          "sha1": "a574a406227fcf2cd92fe3b95f198866f42021f7",
          "md5": "30e5d6c15a6e8daddc099c854c46e76b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "koncat-sample",
          "module": "symbols",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "koncat-sample-lib2-1.0.aar",
          "url": "koncat-sample-lib2-1.0.aar",
          "size": 2317,
          "sha512": "ce27b890cc16cbcfce6aae3c52fcdd85445ec76e05872718698ed23548852fe2ccac7d0709298c3792bd755137fe958896787ce6d13be418570080216e44326a",
          "sha256": "310509022d1089d0ae643a336c6c532e9eb8e3b55b22bb64346bb24a82eb80c3",
          "sha1": "a574a406227fcf2cd92fe3b95f198866f42021f7",
          "md5": "30e5d6c15a6e8daddc099c854c46e76b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "koncat-sample-lib2-1.0-sources.jar",
          "url": "koncat-sample-lib2-1.0-sources.jar",
          "size": 1904,
          "sha512": "05e97c8c325bfd8e86cd8e945a90e1c49c6aeb367938c3b4f346fecb05fec9a2047996eab2f19e9151af99ba981740739071d78e344eedae6d8fed0b6127e8fa",
          "sha256": "ac27faf77c5af74b92225fafe874e7b9bb60c0e3931b9bb45c729b9c5b8a2199",
          "sha1": "dff12c09bb385b318ae0fd5d2597ef7a3f83445c",
          "md5": "eee3f4181ad86c910607da92d46db166"
        }
      ]
    }
  ]
}
