{
  "formatVersion": "1.1",
  "component": {
    "group": "me.2bab",
    "module": "koncat-sample-lib2",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "koncat-sample-lib2-1.0.aar",
          "url": "koncat-sample-lib2-1.0.aar",
          "size": 14591,
          "sha512": "1acc38672cea08cb0832cf2d6bdbbc57e83707b1a27bf1ec53c292bda0a8a481bfec6bd8cd8c91dfa130ce637b90579a05d43e11312e81db80f1f57ccafeb0fd",
          "sha256": "a9086f312da59de208d9aba1a9a04aa6cf8aa1a9b3a4bb785182ee34b8a9e781",
          "sha1": "2da976e6a7de861bd62ab588d25e52d0e822e6ac",
          "md5": "37bbd00e06b3a7d4bd946991037d7634"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "koncat-sample",
          "module": "symbols",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "me.2bab",
          "module": "koncat-runtime",
          "version": {
            "requires": "*"
          }
        }
      ],
      "files": [
        {
          "name": "koncat-sample-lib2-1.0.aar",
          "url": "koncat-sample-lib2-1.0.aar",
          "size": 14591,
          "sha512": "1acc38672cea08cb0832cf2d6bdbbc57e83707b1a27bf1ec53c292bda0a8a481bfec6bd8cd8c91dfa130ce637b90579a05d43e11312e81db80f1f57ccafeb0fd",
          "sha256": "a9086f312da59de208d9aba1a9a04aa6cf8aa1a9b3a4bb785182ee34b8a9e781",
          "sha1": "2da976e6a7de861bd62ab588d25e52d0e822e6ac",
          "md5": "37bbd00e06b3a7d4bd946991037d7634"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "koncat-sample-lib2-1.0-sources.jar",
          "url": "koncat-sample-lib2-1.0-sources.jar",
          "size": 1915,
          "sha512": "255e3e58943a0cdbf91afef9893e0eeaefa27190fe308e1184c8ebb388ea04c5b9b2c6d83eefbde25b2a4672b7ffe06a0c1199cdaa3627296dd64eb6e46a8cfe",
          "sha256": "14a0efa57c47fdf45ce890f238f5157b7795baf1722ebbc04eb2369c7b2100e4",
          "sha1": "51d55eb6035a07cd14c0043cceec6a2834f59c95",
          "md5": "bde55aa9d60d9b6cf26e23603ab34459"
        }
      ]
    }
  ]
}
